<html>
<head>
    <title></title>
     <link rel="stylesheet" type="text/css" href="cipnet.css" />
</head>
<body class="iframe">
    <form>
    <table class="show" width="66%" align="center" border="1"  cellpadding="1" cellspacing="1">
        <tr>
            <td class="title" title="cipnetConfig" colspan="3">
                表计类型说明：
            </td>
        </tr>
        <tr>
            <th>
                表类型
            </th>
            <th>
                子表类型-1
            </th>
            <th>
                子表类型-2
            </th>
        </tr>
        <tr>
            <td>
                电表
            </td>
            <td>
                DTSD342-EN
            </td>
            <td>
                DTSD342-EW
            </td>
        </tr>
        <tr>
            <td>
                水表
            </td>
            <td>
                水表1
            </td>
            <td>
                无
            </td>
        </tr>
        <tr>
            <td>
                气表
            </td>
            <td>
                气表1
            </td>
            <td>
                无
            </td>
        </tr>
        <tr>
            <td>
                热表
            </td>
            <td>
                热表1
            </td>
            <td>
                无
            </td>
        </tr>
    </table>
    </form>
</body>
</html>
